name: Npm.js deploy

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: 'https://registry.npmjs.org'
          scope: igniteui@infragistics.com
      - run: echo ${GITHUB_REF}
      - run: npm version "${GITHUB_REF}" --no-git-tag-version --save
      - run: if [[ "${GITHUB_REF}" == *"alpha"* || "${GITHUB_REF}" == *"beta"* || "${GITHUB_REF}" == *"rc"* ]]; then export NPM_TAG="next"; else export NPM_TAG="latest"; fi
      - run: npm publish --tag ${NPM_TAG}
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}