name: Npm.js deploy

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: 'https://registry.npmjs.org'
      - run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
      - run: echo ${VERSION}
      - run: if [[ "${VERSION}" == *"alpha"* || "${VERSION}" == *"beta"* || "${VERSION}" == *"rc"* ]]; then echo "NPM_TAG=next"; else echo "NPM_TAG=latest"; fi >> $GITHUB_ENV
      - run: echo ${NPM_TAG}
      - run: npm version "${VERSION}" --no-git-tag-version --save
      - run: npm publish --tag ${NPM_TAG}
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}